### PR TITLE
When tracking orders use a product's variant image when available

### PR DESCRIPTION
**Pull request by smockensturm**
if there is one

### CODE REVIEW

**Comment by sjcallender** [comment]
@smockensturm - What problem are you trying to solve with this?

**Comment by smockensturm** [comment]
> @smockensturm - What problem are you trying to solve with this?

We have a field `productImages` on a product. Let's call those common images.

We also use that same field on product **variants**. (If there are any). Let's consider those main images - if you will - different images, different packages let's say.

We want to send the first variant image (if there is one) otherwise send the first product image. Transformed of course.

**Review by johnnynotsolucky — CHANGES_REQUESTED** [review]
Thank you @smockensturm, this is a good idea!

I have just a couple of comments, but otherwise it looks good.

**Comment by smockensturm** [comment]
Hey @johnnynotsolucky fhanks for taking the time to review and explain. Revised per your suggestions.

**Review by johnnynotsolucky — APPROVED** [review]
Thank you @smockensturm, I'll test this out shortly and these changes should be available on the next release!

**Pull request merged**
